API_KEY = "iwpQ6rafmWK5Dfu5V2NQeHaBUWdS81fhzdhjsJQ3jYE0HR3HADXZy0N2jrjV0vany"
SECRET_KEY = "Iw9mxGyYdON1RcTRdD1GnMimVI88WHuQaVpNhao7qFOAWxlFeeyuQ5QUytvqJe7R"

#SYMBOL = "ETH/USD"
#POSITION_SIZE = 0.001

# gridbot settings
##NUM_BUY_GRID_LINES = 5
#NUM_SELL_GRID_LINES = 5
#GRID_SIZE = 2

#CHECK_ORDERS_FREQUENCY = 1
#CLOSED_ORDER_STATUS = 'closed'